/** @type {import('tailwindcss').Config} */
const { 
  colors, 
  baseColors, 
  brandColors, 
  lightTheme,
  spacing, 
  typography,
  textStyles,
  fontWeight,
  borderRadius, 
  fontFamily 
} = require('./src/styles/tokens');

module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Base colors
        primary: baseColors.primary,
        'primary-dark': baseColors.primaryDark,
        'primary-light': baseColors.primaryLight,
        secondary: baseColors.secondary,
        'secondary-dark': baseColors.secondaryDark,
        'secondary-light': baseColors.secondaryLight,
        success: baseColors.success,
        'success-active': baseColors.successActive,
        'success-light': baseColors.successLight,
        'success-accent': baseColors.successAccent,
        error: baseColors.error,
        'error-light': baseColors.errorLight,
        'error-dark': baseColors.errorDark,
        warning: baseColors.warning,
        info: baseColors.info,
        white: baseColors.white,
        black: baseColors.black,
        gray: {
          50: baseColors.gray50,
          100: baseColors.gray100,
          200: baseColors.gray200,
          300: baseColors.gray300,
          400: baseColors.gray400,
          500: baseColors.gray500,
          600: baseColors.gray600,
          700: baseColors.gray700,
          800: baseColors.gray800,
          900: baseColors.gray900,
        },
        
        // Brand colors (reusable)
        brand: {
          purple: brandColors.purple,
          'purple-dark': brandColors.purpleDark,
          red: brandColors.red,
          'red-dark': brandColors.redDark,
        },
        
        // Theme colors (light theme by default, can be extended for dark mode)
        theme: {
          background: lightTheme.background,
          'background-secondary': lightTheme.backgroundSecondary,
          'background-tertiary': lightTheme.backgroundTertiary,
          'background-card': lightTheme.backgroundCard,
          'background-overlay': lightTheme.backgroundOverlay,
          'text-primary': lightTheme.textPrimary,
          'text-secondary': lightTheme.textSecondary,
          'text-base-secondary': lightTheme.textBaseSecondary,
          'text-tertiary': lightTheme.textTertiary,
          'text-inverse': lightTheme.textInverse,
          'text-disabled': lightTheme.textDisabled,
          border: lightTheme.border,
          'border-light': lightTheme.borderLight,
          'border-dark': lightTheme.borderDark,
          muted: lightTheme.muted,
          'muted-dark': lightTheme.mutedDark,
          interactive: lightTheme.interactive,
          'interactive-hover': lightTheme.interactiveHover,
          'interactive-active': lightTheme.interactiveActive,
          'pagination-active': lightTheme.paginationActive,
          'pagination-inactive': lightTheme.paginationInactive,
        },
        
        // Legacy semantic colors (backward compatibility)
        background: colors.background,
        'background-secondary': colors.backgroundSecondary,
        'background-tertiary': colors.backgroundTertiary,
        'text-primary': colors.textPrimary,
        'text-secondary': colors.textSecondary,
        'text-tertiary': colors.textTertiary,
        'text-inverse': colors.textInverse,
        border: colors.border,
        'border-light': colors.borderLight,
        'border-dark': colors.borderDark,
        muted: colors.muted,
        'muted-dark': colors.mutedDark,
        
        // Legacy screen-specific colors (backward compatibility - use theme tokens instead)
        'splash-bg': colors.splashBackground,
        'splash-logo-red': colors.splashLogoRed,
        'onboarding-bg': colors.onboardingBackground,
        'onboarding-card-bg': colors.onboardingCardBackground,
        'onboarding-card-border': colors.onboardingCardBorder,
        'onboarding-text-primary': colors.onboardingTextPrimary,
        'onboarding-text-secondary': colors.onboardingTextSecondary,
        'onboarding-brand-purple': colors.onboardingBrandPurple,
        'onboarding-brand-red': colors.onboardingBrandRed,
        'onboarding-pagination-active': colors.onboardingPaginationActive,
        'onboarding-pagination-inactive': colors.onboardingPaginationInactive,
      },
      spacing: {
        xs: `${spacing.xs}px`,
        sm: `${spacing.sm}px`,
        md: `${spacing.md}px`,
        lg: `${spacing.lg}px`,
        xl: `${spacing.xl}px`,
        '2xl': `${spacing['2xl']}px`,
        '3xl': `${spacing['3xl']}px`,
        '4xl': `${spacing['4xl']}px`,
        // Splash screen spacing (responsive based on 390px base)
        'splash-status-bar': `${spacing.splashStatusBar}px`,
        'splash-status-padding': `${spacing.splashStatusBarPadding}px`,
        'splash-status-top': `${spacing.splashStatusBarTop}px`,
        'splash-text-left': `${spacing.splashTextGroupLeft}px`,
        'splash-text-top': `${spacing.splashTextGroupTop}px`,
        'splash-text-width': `${spacing.splashTextGroupWidth}px`,
        'splash-text-gap': `${spacing.splashTextGroupGap}px`,
        'splash-logo-left': `${spacing.splashLogoLeft}px`,
        'splash-logo-top': `${spacing.splashLogoTop}px`,
        'splash-logo-h': `${spacing.splashLogoHeight}px`,
        'splash-logo-red-w': `${spacing.splashLogoRedWidth}px`,
        'splash-logo-white-w': `${spacing.splashLogoWhiteWidth}px`,
        'splash-footer-bottom': `${spacing.splashFooterBottom}px`,
        'splash-footer-left': `${spacing.splashFooterLeft}px`,
        'splash-footer-width': `${spacing.splashFooterWidth}px`,
        // Onboarding screen spacing
        'onboarding-header-padding': `${spacing.onboardingHeaderPadding}px`,
        'onboarding-content-padding': `${spacing.onboardingContentPadding}px`,
        'onboarding-card-padding': `${spacing.onboardingCardPadding}px`,
        'onboarding-card-width': `${spacing.onboardingCardWidth}px`,
        'onboarding-card-height': `${spacing.onboardingCardHeight}px`,
        'onboarding-image-width': `${spacing.onboardingImageWidth}px`,
        'onboarding-image-height': `${spacing.onboardingImageHeight}px`,
        'onboarding-button-gap': `${spacing.onboardingButtonGap}px`,
        'onboarding-pagination-gap': `${spacing.onboardingPaginationGap}px`,
        'onboarding-pagination-dot': `${spacing.onboardingPaginationDotSize}px`,
      },
      fontSize: {
        // Reusable typography tokens
        'display-large': [`${typography.displayLarge.fontSize}px`, { lineHeight: `${typography.displayLarge.lineHeight}px`, fontWeight: typography.displayLarge.fontWeight, letterSpacing: `${typography.displayLarge.letterSpacing}px` }],
        'display-medium': [`${typography.displayMedium.fontSize}px`, { lineHeight: `${typography.displayMedium.lineHeight}px`, fontWeight: typography.displayMedium.fontWeight }],
        h1: [`${typography.h1.fontSize}px`, { lineHeight: `${typography.h1.lineHeight}px`, fontWeight: typography.h1.fontWeight }],
        h2: [`${typography.h2.fontSize}px`, { lineHeight: `${typography.h2.lineHeight}px`, fontWeight: typography.h2.fontWeight }],
        h3: [`${typography.h3.fontSize}px`, { lineHeight: `${typography.h3.lineHeight}px`, fontWeight: typography.h3.fontWeight }],
        h4: [`${typography.h4.fontSize}px`, { lineHeight: `${typography.h4.lineHeight}px`, fontWeight: typography.h4.fontWeight }],
        body: [`${typography.body.fontSize}px`, { lineHeight: `${typography.body.lineHeight}px`, fontWeight: typography.body.fontWeight }],
        'body-small': [`${typography.bodySmall.fontSize}px`, { lineHeight: `${typography.bodySmall.lineHeight}px`, fontWeight: typography.bodySmall.fontWeight }],
        'body-small-tight': [`${typography.bodySmallTight.fontSize}px`, { lineHeight: `${typography.bodySmallTight.lineHeight}px`, fontWeight: typography.bodySmallTight.fontWeight }],
        'body-tight': [`${typography.bodyTight.fontSize}px`, { lineHeight: `${typography.bodyTight.lineHeight}px`, fontWeight: typography.bodyTight.fontWeight, letterSpacing: `${typography.bodyTight.letterSpacing}px` }],
        button: [`${typography.button.fontSize}px`, { lineHeight: `${typography.button.lineHeight}px`, fontWeight: typography.button.fontWeight }],
        label: [`${typography.label.fontSize}px`, { lineHeight: `${typography.label.lineHeight}px`, fontWeight: typography.label.fontWeight }],
        caption: [`${typography.caption.fontSize}px`, { lineHeight: `${typography.caption.lineHeight}px`, fontWeight: typography.caption.fontWeight }],
        overline: [`${typography.overline.fontSize}px`, { lineHeight: `${typography.overline.lineHeight}px`, fontWeight: typography.overline.fontWeight, letterSpacing: `${typography.overline.letterSpacing}px` }],
        nav: [`${typography.nav.fontSize}px`, { lineHeight: `${typography.nav.lineHeight}px`, fontWeight: typography.nav.fontWeight, textTransform: typography.nav.textTransform }],
        'status-bar': [`${typography.statusBar.fontSize}px`, { lineHeight: `${typography.statusBar.lineHeight}px`, fontWeight: typography.statusBar.fontWeight, letterSpacing: `${typography.statusBar.letterSpacing}px` }],
        
        // Legacy screen-specific typography (backward compatibility - use reusable tokens instead)
        'splash-name': [`${typography.splashName.fontSize}px`, { lineHeight: `${typography.splashName.lineHeight}px`, fontWeight: typography.splashName.fontWeight, letterSpacing: `${typography.splashName.letterSpacing}px` }],
        'splash-from-stc': [`${typography.splashFromStc.fontSize}px`, { lineHeight: `${typography.splashFromStc.lineHeight}px`, fontWeight: typography.splashFromStc.fontWeight, letterSpacing: `${typography.splashFromStc.letterSpacing}px` }],
        'splash-footer': [`${typography.splashFooter.fontSize}px`, { lineHeight: `${typography.splashFooter.lineHeight}px`, fontWeight: typography.splashFooter.fontWeight, letterSpacing: `${typography.splashFooter.letterSpacing}px` }],
        'splash-time': [`${typography.splashTime.fontSize}px`, { lineHeight: `${typography.splashTime.lineHeight}px`, fontWeight: typography.splashTime.fontWeight, letterSpacing: `${typography.splashTime.letterSpacing}px` }],
        'onboarding-header': [`${typography.onboardingHeader.fontSize}px`, { lineHeight: `${typography.onboardingHeader.lineHeight}px`, fontWeight: typography.onboardingHeader.fontWeight, textTransform: typography.onboardingHeader.textTransform }],
        'onboarding-title': [`${typography.onboardingTitle.fontSize}px`, { lineHeight: `${typography.onboardingTitle.lineHeight}px`, fontWeight: typography.onboardingTitle.fontWeight }],
        'onboarding-subtitle': [`${typography.onboardingSubtitle.fontSize}px`, { lineHeight: `${typography.onboardingSubtitle.lineHeight}px`, fontWeight: typography.onboardingSubtitle.fontWeight }],
        'onboarding-description': [`${typography.onboardingDescription.fontSize}px`, { lineHeight: `${typography.onboardingDescription.lineHeight}px`, fontWeight: typography.onboardingDescription.fontWeight }],
        'onboarding-slide-title': [`${typography.onboardingSlideTitle.fontSize}px`, { lineHeight: `${typography.onboardingSlideTitle.lineHeight}px`, fontWeight: typography.onboardingSlideTitle.fontWeight }],
        'onboarding-slide-description': [`${typography.onboardingSlideDescription.fontSize}px`, { lineHeight: `${typography.onboardingSlideDescription.lineHeight}px`, fontWeight: typography.onboardingSlideDescription.fontWeight }],
        
        // Composite text style tokens (convenient size + weight combinations)
        'text-title': [`${textStyles.title.fontSize}px`, { lineHeight: `${textStyles.title.lineHeight}px`, fontWeight: textStyles.title.fontWeight }],
        'text-title-large': [`${textStyles['title-large'].fontSize}px`, { lineHeight: `${textStyles['title-large'].lineHeight}px`, fontWeight: textStyles['title-large'].fontWeight, letterSpacing: `${textStyles['title-large'].letterSpacing}px` }],
        'text-title-medium': [`${textStyles['title-medium'].fontSize}px`, { lineHeight: `${textStyles['title-medium'].lineHeight}px`, fontWeight: textStyles['title-medium'].fontWeight }],
        'text-title-small': [`${textStyles['title-small'].fontSize}px`, { lineHeight: `${textStyles['title-small'].lineHeight}px`, fontWeight: textStyles['title-small'].fontWeight }],
        'text-subtitle': [`${textStyles.subtitle.fontSize}px`, { lineHeight: `${textStyles.subtitle.lineHeight}px`, fontWeight: textStyles.subtitle.fontWeight }],
        'text-subtitle-bold': [`${textStyles['subtitle-bold'].fontSize}px`, { lineHeight: `${textStyles['subtitle-bold'].lineHeight}px`, fontWeight: textStyles['subtitle-bold'].fontWeight }],
        'text-subtitle-small': [`${textStyles['subtitle-small'].fontSize}px`, { lineHeight: `${textStyles['subtitle-small'].lineHeight}px`, fontWeight: textStyles['subtitle-small'].fontWeight }],
        'text-text': [`${textStyles.text.fontSize}px`, { lineHeight: `${textStyles.text.lineHeight}px`, fontWeight: textStyles.text.fontWeight }],
        'text-text-bold': [`${textStyles['text-bold'].fontSize}px`, { lineHeight: `${textStyles['text-bold'].lineHeight}px`, fontWeight: textStyles['text-bold'].fontWeight }],
        'text-text-semibold': [`${textStyles['text-semibold'].fontSize}px`, { lineHeight: `${textStyles['text-semibold'].lineHeight}px`, fontWeight: textStyles['text-semibold'].fontWeight }],
        'text-text-medium': [`${textStyles['text-medium'].fontSize}px`, { lineHeight: `${textStyles['text-medium'].lineHeight}px`, fontWeight: textStyles['text-medium'].fontWeight }],
        'text-text-small': [`${textStyles['text-small'].fontSize}px`, { lineHeight: `${textStyles['text-small'].lineHeight}px`, fontWeight: textStyles['text-small'].fontWeight }],
        'text-text-small-tight': [`${textStyles['text-small-tight'].fontSize}px`, { lineHeight: `${textStyles['text-small-tight'].lineHeight}px`, fontWeight: textStyles['text-small-tight'].fontWeight }],
        'text-text-small-bold': [`${textStyles['text-small-bold'].fontSize}px`, { lineHeight: `${textStyles['text-small-bold'].lineHeight}px`, fontWeight: textStyles['text-small-bold'].fontWeight }],
        'text-text-small-semibold': [`${textStyles['text-small-semibold'].fontSize}px`, { lineHeight: `${textStyles['text-small-semibold'].lineHeight}px`, fontWeight: textStyles['text-small-semibold'].fontWeight }],
        'text-text-small-medium': [`${textStyles['text-small-medium'].fontSize}px`, { lineHeight: `${textStyles['text-small-medium'].lineHeight}px`, fontWeight: textStyles['text-small-medium'].fontWeight }],
        'text-caption': [`${textStyles.caption.fontSize}px`, { lineHeight: `${textStyles.caption.lineHeight}px`, fontWeight: textStyles.caption.fontWeight }],
        'text-caption-bold': [`${textStyles['caption-bold'].fontSize}px`, { lineHeight: `${textStyles['caption-bold'].lineHeight}px`, fontWeight: textStyles['caption-bold'].fontWeight }],
        'text-caption-medium': [`${textStyles['caption-medium'].fontSize}px`, { lineHeight: `${textStyles['caption-medium'].lineHeight}px`, fontWeight: textStyles['caption-medium'].fontWeight }],
        'text-label': [`${textStyles.label.fontSize}px`, { lineHeight: `${textStyles.label.lineHeight}px`, fontWeight: textStyles.label.fontWeight }],
        'text-label-bold': [`${textStyles['label-bold'].fontSize}px`, { lineHeight: `${textStyles['label-bold'].lineHeight}px`, fontWeight: textStyles['label-bold'].fontWeight }],
        'text-label-semibold': [`${textStyles['label-semibold'].fontSize}px`, { lineHeight: `${textStyles['label-semibold'].lineHeight}px`, fontWeight: textStyles['label-semibold'].fontWeight }],
      },
      fontWeight: {
        thin: fontWeight.thin,
        light: fontWeight.light,
        regular: fontWeight.regular,
        normal: fontWeight.regular, // Alias for regular
        medium: fontWeight.medium,
        semibold: fontWeight.semibold,
        bold: fontWeight.bold,
        extrabold: fontWeight.extrabold,
        black: fontWeight.black,
      },
      borderRadius: {
        none: `${borderRadius.none}px`,
        sm: `${borderRadius.sm}px`,
        md: `${borderRadius.md}px`,
        lg: `${borderRadius.lg}px`,
        xl: `${borderRadius.xl}px`,
        '2xl': `${borderRadius['2xl']}px`,
        full: `${borderRadius.full}px`,
      },
      fontFamily: {
        primary: [fontFamily.primary],
        system: [fontFamily.system],
      },
    },
  },
  plugins: [],
};

